In [44]:
import os
from pathlib import Path

import polars as pl
from sklearn.model_selection import train_test_split

In [45]:
DATASET_PATH = Path("datasets/dataset_20260707.csv")

In [46]:
DATABASE_URI = os.environ["DATABASE_URI"]

In [47]:
RANDOM_SEED = 42

# Chargement des données

In [48]:
df_dataset = pl.read_csv(DATASET_PATH, schema_overrides={"cluster_id": pl.String})

In [49]:
df_dataset

shape: (2_129, 4)
┌──────────────────────────────┬─────────────────────────────┬───────┬─────────────────────────────┐
│ identifiant_unique_i         ┆ identifiant_unique_j        ┆ label ┆ cluster_id                  │
│ ---                          ┆ ---                         ┆ ---   ┆ ---                         │
│ str                          ┆ str                         ┆ bool  ┆ str                         │
╞══════════════════════════════╪═════════════════════════════╪═══════╪═════════════════════════════╡
│ 07e07779-388e-5971-947b-b999 ┆ lokki_67692fc641d8badbf051e ┆ true  ┆ 7758461304653219539         │
│ ae…                          ┆ c32                         ┆       ┆                             │
│ 085352c0-77c6-599d-b54a-02ef ┆ 772950c8-5202-5394-b0ae-8eb ┆ false ┆ null                        │
│ 2a…                          ┆ bda…                        ┆       ┆                             │
│ 085352c0-77c6-599d-b54a-02ef ┆ citeo_5487990001            ┆ false ┆ null                        │
│ 2a…                          ┆                             ┆       ┆                             │
│ 085352c0-77c6-599d-b54a-02ef ┆ citeo_5488009001            ┆ false ┆ null                        │
│ 2a…                          ┆                             ┆       ┆                             │
│ 085352c0-77c6-599d-b54a-02ef ┆ citeo_5488015001            ┆ false ┆ null                        │
│ 2a…                          ┆                             ┆       ┆                             │
│ …                            ┆ …                           ┆ …     ┆ …                           │
│ refashion_TLC-REFASHION-PAV- ┆ refashion_TLC-REFASHION-PAV ┆ true  ┆ 9a14e7d6-f708-58fd-bcbb-3d3 │
│ 32…                          ┆ -34…                        ┆       ┆ c2c…                        │
│ refashion_TLC-REFASHION-PAV- ┆ refashion_TLC-REFASHION-PAV ┆ true  ┆ 1f8fb158-8b9a-54b5-81ca-d9d │
│ 33…                          ┆ -34…                        ┆       ┆ 542…                        │
│ refashion_TLC-REFASHION-PAV- ┆ refashion_TLC-REFASHION-PAV ┆ true  ┆ 05f37598-e1d8-40a1-bb9b-5be │
│ 33…                          ┆ -34…                        ┆       ┆ 142…                        │
│ refashion_TLC-REFASHION-PAV- ┆ refashion_TLC-REFASHION-PAV ┆ true  ┆ 02d7266e-e174-4c21-a897-bd0 │
│ 33…                          ┆ -34…                        ┆       ┆ 8b0…                        │
│ repair_cafe_216              ┆ repair_cafe_poissy_le_champ ┆ true  ┆ 00a193b3-b145-5f06-aa29-515 │
│                              ┆ _de…                        ┆       ┆ d1f…                        │
└──────────────────────────────┴─────────────────────────────┴───────┴─────────────────────────────┘

In [50]:
df_dataset.group_by("label").len()

shape: (2, 2)
┌───────┬──────┐
│ label ┆ len  │
│ ---   ┆ ---  │
│ bool  ┆ u32  │
╞═══════╪══════╡
│ true  ┆ 1129 │
│ false ┆ 1000 │
└───────┴──────┘

# Chargement des variables d'intérêt depuis la base

In [22]:
df_dataset.write_database(
    "luis.dataset_tmp", connection=DATABASE_URI, if_table_exists="replace"
)

129

In [23]:
sql_dataset_features = """
with actions_by_actor as (
-- D'abord on calcule les actions des parents sur la base de leurs enfants
select 
	qv.identifiant_unique as acteur_id,
	(1 = any(array_agg(qv2.action_id))) as action_reparer,
	(2 = any(array_agg(qv2.action_id))) as action_acheter,
	(3 = any(array_agg(qv2.action_id))) as action_revendre,
	(4 = any(array_agg(qv2.action_id))) as action_donner,
	(5 = any(array_agg(qv2.action_id))) as action_louer,
	(6 = any(array_agg(qv2.action_id))) as action_mettreenlocation,
	(7 = any(array_agg(qv2.action_id))) as action_emprunter,
	(8 = any(array_agg(qv2.action_id))) as action_preter,
	(9 = any(array_agg(qv2.action_id))) as action_echanger,
	(11 = any(array_agg(qv2.action_id))) as action_trier,
	(12 = any(array_agg(qv2.action_id))) as action_rapporter
from
	qfdmo_vueacteur qv
inner join qfdmo_vueacteur qv3 on
	qv.est_parent
	and qv.identifiant_unique = qv3.parent_id
	and qv3.statut <> 'SUPPRIME'
inner join qfdmo_vuepropositionservice qv2 on
	qv3.identifiant_unique = qv2.acteur_id
group by
	1
union all -- on joint les actions des enfants
select
	acteur_id,
	(1 = any(array_agg(action_id))) as action_reparer,
	(2 = any(array_agg(action_id))) as action_acheter,
	(3 = any(array_agg(action_id))) as action_revendre,
	(4 = any(array_agg(action_id))) as action_donner,
	(5 = any(array_agg(action_id))) as action_louer,
	(6 = any(array_agg(action_id))) as action_mettreenlocation,
	(7 = any(array_agg(action_id))) as action_emprunter,
	(8 = any(array_agg(action_id))) as action_preter,
	(9 = any(array_agg(action_id))) as action_echanger,
	(11 = any(array_agg(action_id))) as action_trier,
	(12 = any(array_agg(action_id))) as action_rapporter
from
	qfdmo_vuepropositionservice
group by
	acteur_id
),
-- Sélection des variables à la maille acteur avec les actions précédemment sélectionnées
features as (
select
	identifiant_unique,
	nom,
	description,
	acteur_type_id,
	adresse,
	adresse_complement,
	code_postal,
	ville,
	url,
	email,
	"location",
	telephone,
	nom_commercial,
	nom_officiel,
	siren,
	siret,
	source_id,
	naf_principal,
	horaires_osm,
	horaires_description,
	public_accueilli,
	reprise,
	exclusivite_de_reprisereparation,
	uniquement_sur_rdv,
	consignes_dacces,
	action_principale_id,
	lieu_prestation,
	latitude,
	longitude,
	code_commune_insee,
	epci_id,
	aba.*
from
	qfdmo_vueacteur qv
left join actions_by_actor aba on
	qv.identifiant_unique = aba.acteur_id)
-- Join avec les acteurs sélectionnés dans le dataset
select 
	dt.*,
	f.nom as nom_i,
	f.description as description_i,
	f.acteur_type_id as acteur_type_id_i,
	f.adresse as adresse_i,
	f.adresse_complement as adresse_complement_i,
	f.code_postal as code_postal_i,
	f.ville as ville_i,
	f.url as url_i,
	f.email as email_i,
	f.telephone as telephone_i,
	f.nom_commercial as nom_commercial_i,
	f.nom_officiel as nom_officiel_i,
	f.siren as siren_i,
	f.siret as siret_i,
	f.source_id as source_id_i,
	f.naf_principal as naf_principal_i,
	f.horaires_osm as horaires_osm_i,
	f.horaires_description as horaires_description_i,
	f.public_accueilli as public_accueilli_i,
	f.reprise as reprise_i,
	f.exclusivite_de_reprisereparation as exclusivite_de_reprisereparation_i,
	f.uniquement_sur_rdv as uniquement_sur_rdv_i,
	f.consignes_dacces as consignes_dacces_i,
	f.action_principale_id as action_principale_id_i,
	f.lieu_prestation as lieu_prestation_i,
	f.latitude as latitude_i,
	f.longitude as longitude_i,
	f.code_commune_insee as code_commune_insee_i,
	f.epci_id as epci_id_i,
	f.action_reparer as action_reparer_i,
	f.action_acheter as action_acheter_i,
	f.action_revendre as action_revendre_i,
	f.action_donner as action_donner_i,
	f.action_louer as action_louer_i,
	f.action_mettreenlocation as action_mettreenlocation_i,
	f.action_emprunter as action_emprunter_i,
	f.action_preter as action_preter_i,
	f.action_echanger as action_echanger_i,
	f.action_trier as action_trier_i,
	f.action_rapporter as action_rapporter_i,
	f2.nom as nom_j,
	f2.description as description_j,
	f2.acteur_type_id as acteur_type_id_j,
	f2.adresse as adresse_j,
	f2.adresse_complement as adresse_complement_j,
	f2.code_postal as code_postal_j,
	f2.ville as ville_j,
	f2.url as url_j,
	f2.email as email_j,
	f2.telephone as telephone_j,
	f2.nom_commercial as nom_commercial_j,
	f2.nom_officiel as nom_officiel_j,
	f2.siren as siren_j,
	f2.siret as siret_j,
	f2.source_id as source_id_j,
	f2.naf_principal as naf_principal_j,
	f2.horaires_osm as horaires_osm_j,
	f2.horaires_description as horaires_description_j,
	f2.public_accueilli as public_accueilli_j,
	f2.reprise as reprise_j,
	f2.exclusivite_de_reprisereparation as exclusivite_de_reprisereparation_j,
	f2.uniquement_sur_rdv as uniquement_sur_rdv_j,
	f2.consignes_dacces as consignes_dacces_j,
	f2.action_principale_id as action_principale_id_j,
	f2.lieu_prestation as lieu_prestation_j,
	f2.latitude as latitude_j,
	f2.longitude as longitude_j,
	f2.code_commune_insee as code_commune_insee_j,
	f2.epci_id as epci_id_j,
	f2.action_reparer as action_reparer_j,
	f2.action_acheter as action_acheter_j,
	f2.action_revendre as action_revendre_j,
	f2.action_donner as action_donner_j,
	f2.action_louer as action_louer_j,
	f2.action_mettreenlocation as action_mettreenlocation_j,
	f2.action_emprunter as action_emprunter_j,
	f2.action_preter as action_preter_j,
	f2.action_echanger as action_echanger_j,
	f2.action_trier as action_trier_j,
	f2.action_rapporter as action_rapporter_j
from
	luis.dataset_tmp dt
left join features f on
	dt.identifiant_unique_i = f.identifiant_unique
left join features f2 on
	dt.identifiant_unique_j = f2.identifiant_unique
"""

In [24]:
df_features = pl.read_database_uri(sql_dataset_features, uri=DATABASE_URI)

In [51]:
df_features.shape

(2129, 84)

In [52]:
# Assert no duplicates
assert df_features.group_by(
    ["identifiant_unique_i", "identifiant_unique_j"]
).len().select(pl.col("len")).sum().item() == len(df_features)

In [53]:
df_features.describe()

shape: (9, 85)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ identifia ┆ identifia ┆ label    ┆ … ┆ action_pr ┆ action_ec ┆ action_tr ┆ action_ra │
│ ---       ┆ nt_unique ┆ nt_unique ┆ ---      ┆   ┆ eter_j    ┆ hanger_j  ┆ ier_j     ┆ pporter_j │
│ str       ┆ _i        ┆ _j        ┆ f64      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ ---       ┆ ---       ┆          ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
│           ┆ str       ┆ str       ┆          ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 2129      ┆ 2129      ┆ 2129.0   ┆ … ┆ 2118.0    ┆ 2118.0    ┆ 2118.0    ┆ 2118.0    │
│ null_coun ┆ 0         ┆ 0         ┆ 0.0      ┆ … ┆ 11.0      ┆ 11.0      ┆ 11.0      ┆ 11.0      │
│ t         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ null      ┆ null      ┆ 0.530296 ┆ … ┆ 0.0       ┆ 0.007082  ┆ 0.77526   ┆ 0.009443  │
│ std       ┆ null      ┆ null      ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ min       ┆ 00a193b3- ┆ 1e0bfede- ┆ 0.0      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│           ┆ b145-5f06 ┆ 8c6b-5469 ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆ -aa29-515 ┆ -9b92-b45 ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆ d1f…      ┆ 8bf…      ┆          ┆   ┆           ┆           ┆           ┆           │
│ 25%       ┆ null      ┆ null      ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 50%       ┆ null      ┆ null      ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 75%       ┆ null      ┆ null      ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ max       ┆ uniqueapp ┆ zone__8_1 ┆ 1.0      ┆ … ┆ 0.0       ┆ 1.0       ┆ 1.0       ┆ 1.0       │
│           ┆ _unique_6 ┆ 09247_rep ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆ 2390804d9 ┆ aration   ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆ 5b5…      ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

# Traitement des "__empty__"

In [54]:
df_features_preprocessed = df_features.with_columns(
    pl.selectors.by_dtype(pl.String)
    .exclude("cluster_id")
    .str.strip_chars()
    .replace("__empty__", None)
    .replace("", None)
)

In [55]:
df_features_preprocessed.describe()

shape: (9, 85)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ identifia ┆ identifia ┆ label    ┆ … ┆ action_pr ┆ action_ec ┆ action_tr ┆ action_ra │
│ ---       ┆ nt_unique ┆ nt_unique ┆ ---      ┆   ┆ eter_j    ┆ hanger_j  ┆ ier_j     ┆ pporter_j │
│ str       ┆ _i        ┆ _j        ┆ f64      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ ---       ┆ ---       ┆          ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
│           ┆ str       ┆ str       ┆          ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 2129      ┆ 2129      ┆ 2129.0   ┆ … ┆ 2118.0    ┆ 2118.0    ┆ 2118.0    ┆ 2118.0    │
│ null_coun ┆ 0         ┆ 0         ┆ 0.0      ┆ … ┆ 11.0      ┆ 11.0      ┆ 11.0      ┆ 11.0      │
│ t         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ null      ┆ null      ┆ 0.530296 ┆ … ┆ 0.0       ┆ 0.007082  ┆ 0.77526   ┆ 0.009443  │
│ std       ┆ null      ┆ null      ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ min       ┆ 00a193b3- ┆ 1e0bfede- ┆ 0.0      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│           ┆ b145-5f06 ┆ 8c6b-5469 ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆ -aa29-515 ┆ -9b92-b45 ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆ d1f…      ┆ 8bf…      ┆          ┆   ┆           ┆           ┆           ┆           │
│ 25%       ┆ null      ┆ null      ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 50%       ┆ null      ┆ null      ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 75%       ┆ null      ┆ null      ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ max       ┆ uniqueapp ┆ zone__8_1 ┆ 1.0      ┆ … ┆ 0.0       ┆ 1.0       ┆ 1.0       ┆ 1.0       │
│           ┆ _unique_6 ┆ 09247_rep ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆ 2390804d9 ┆ aration   ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆ 5b5…      ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

# Traitement de l'absence de latitude/longitude

In [56]:
df_features_preprocessed = df_features_preprocessed.with_columns(
    pl.selectors.contains("latitude", "longitude").fill_null(0)
)

In [57]:
df_features_preprocessed.describe()

shape: (9, 85)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ identifia ┆ identifia ┆ label    ┆ … ┆ action_pr ┆ action_ec ┆ action_tr ┆ action_ra │
│ ---       ┆ nt_unique ┆ nt_unique ┆ ---      ┆   ┆ eter_j    ┆ hanger_j  ┆ ier_j     ┆ pporter_j │
│ str       ┆ _i        ┆ _j        ┆ f64      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ ---       ┆ ---       ┆          ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
│           ┆ str       ┆ str       ┆          ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 2129      ┆ 2129      ┆ 2129.0   ┆ … ┆ 2118.0    ┆ 2118.0    ┆ 2118.0    ┆ 2118.0    │
│ null_coun ┆ 0         ┆ 0         ┆ 0.0      ┆ … ┆ 11.0      ┆ 11.0      ┆ 11.0      ┆ 11.0      │
│ t         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ null      ┆ null      ┆ 0.530296 ┆ … ┆ 0.0       ┆ 0.007082  ┆ 0.77526   ┆ 0.009443  │
│ std       ┆ null      ┆ null      ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ min       ┆ 00a193b3- ┆ 1e0bfede- ┆ 0.0      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│           ┆ b145-5f06 ┆ 8c6b-5469 ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆ -aa29-515 ┆ -9b92-b45 ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆ d1f…      ┆ 8bf…      ┆          ┆   ┆           ┆           ┆           ┆           │
│ 25%       ┆ null      ┆ null      ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 50%       ┆ null      ┆ null      ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 75%       ┆ null      ┆ null      ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ max       ┆ uniqueapp ┆ zone__8_1 ┆ 1.0      ┆ … ┆ 0.0       ┆ 1.0       ┆ 1.0       ┆ 1.0       │
│           ┆ _unique_6 ┆ 09247_rep ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆ 2390804d9 ┆ aration   ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆ 5b5…      ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

# Ajout de cluster_ids pour les négatifs afin de faciliter les splits

In [72]:
df_features_preprocessed = df_features_preprocessed.with_columns(
    pl.coalesce(
        [
            "cluster_id",
            pl.concat_str(
                "identifiant_unique_i", "identifiant_unique_j", separator="___"
            ),
        ]
    ).alias("cluster_id")
)

# Train/test split

In [73]:
train_cluster_ids, test_cluster_ids = train_test_split(
    df_features_preprocessed.select("cluster_id").unique("cluster_id"),
    test_size=0.2,
    random_state=RANDOM_SEED,
)

In [74]:
len(train_cluster_ids), len(test_cluster_ids)

(940, 235)

In [75]:
train_cluster_ids

shape: (940, 1)
┌─────────────────────────────────┐
│ cluster_id                      │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ ecosystem_EEE-ecosystem-C-1030… │
│ BIB2644.0___mbs_industrie_1988… │
│ BIB13312.0___BIB13321.0         │
│ ecologic_93-DF669-01___ocab_va… │
│ 47e7f597-42fe-5292-82eb-716aab… │
│ …                               │
│ BAL_44.7109809, 1.904558___ali… │
│ aliapur_131015000000005___bout… │
│ 772950c8-5202-5394-b0ae-8ebbda… │
│ corepile_07-DIS-0314___ordrede… │
│ 02d7266e-e174-4c21-a897-bd08b0… │
└─────────────────────────────────┘

In [77]:
df_features_preprocessed_split = df_features_preprocessed.with_columns().with_columns(
    pl.when(
        pl.col("cluster_id").is_in(train_cluster_ids.get_column("cluster_id").to_list())
    )
    .then(pl.lit("train"))
    .when(
        pl.col("cluster_id").is_in(test_cluster_ids.get_column("cluster_id").to_list())
    )
    .then(pl.lit("test"))
    .otherwise(pl.lit("unknown"))
    .alias("split")
)

In [78]:
df_features_preprocessed_split

shape: (2_129, 85)
┌─────────────┬────────────┬───────┬────────────┬───┬────────────┬────────────┬────────────┬───────┐
│ identifiant ┆ identifian ┆ label ┆ cluster_id ┆ … ┆ action_ech ┆ action_tri ┆ action_rap ┆ split │
│ _unique_i   ┆ t_unique_j ┆ ---   ┆ ---        ┆   ┆ anger_j    ┆ er_j       ┆ porter_j   ┆ ---   │
│ ---         ┆ ---        ┆ bool  ┆ str        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ str   │
│ str         ┆ str        ┆       ┆            ┆   ┆ bool       ┆ bool       ┆ bool       ┆       │
╞═════════════╪════════════╪═══════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════╡
│ 00a193b3-b1 ┆ repair_caf ┆ true  ┆ 00a193b3-b ┆ … ┆ false      ┆ false      ┆ false      ┆ train │
│ 45-5f06-aa2 ┆ e_poissy_l ┆       ┆ 145-5f06-a ┆   ┆            ┆            ┆            ┆       │
│ 9-515d1f…   ┆ e_champ_de ┆       ┆ a29-515d1f ┆   ┆            ┆            ┆            ┆       │
│             ┆ …          ┆       ┆ …          ┆   ┆            ┆            ┆            ┆       │
│ 00a193b3-b1 ┆ repair_caf ┆ true  ┆ 00a193b3-b ┆ … ┆ false      ┆ false      ┆ false      ┆ train │
│ 45-5f06-aa2 ┆ e_216      ┆       ┆ 145-5f06-a ┆   ┆            ┆            ┆            ┆       │
│ 9-515d1f…   ┆            ┆       ┆ a29-515d1f ┆   ┆            ┆            ┆            ┆       │
│             ┆            ┆       ┆ …          ┆   ┆            ┆            ┆            ┆       │
│ 016ab333-09 ┆ citeo_1627 ┆ true  ┆ 016ab333-0 ┆ … ┆ false      ┆ true       ┆ false      ┆ train │
│ b6-5ee9-a35 ┆ 076001     ┆       ┆ 9b6-5ee9-a ┆   ┆            ┆            ┆            ┆       │
│ b-e38c5f…   ┆            ┆       ┆ 35b-e38c5f ┆   ┆            ┆            ┆            ┆       │
│             ┆            ┆       ┆ …          ┆   ┆            ┆            ┆            ┆       │
│ 016ab333-09 ┆ citeo_1627 ┆ true  ┆ 016ab333-0 ┆ … ┆ false      ┆ true       ┆ false      ┆ train │
│ b6-5ee9-a35 ┆ 076002     ┆       ┆ 9b6-5ee9-a ┆   ┆            ┆            ┆            ┆       │
│ b-e38c5f…   ┆            ┆       ┆ 35b-e38c5f ┆   ┆            ┆            ┆            ┆       │
│             ┆            ┆       ┆ …          ┆   ┆            ┆            ┆            ┆       │
│ 016ab333-09 ┆ citeo_1627 ┆ true  ┆ 016ab333-0 ┆ … ┆ false      ┆ true       ┆ false      ┆ train │
│ b6-5ee9-a35 ┆ 076003     ┆       ┆ 9b6-5ee9-a ┆   ┆            ┆            ┆            ┆       │
│ b-e38c5f…   ┆            ┆       ┆ 35b-e38c5f ┆   ┆            ┆            ┆            ┆       │
│             ┆            ┆       ┆ …          ┆   ┆            ┆            ┆            ┆       │
│ …           ┆ …          ┆ …     ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …     │
│ ristart_149 ┆ uniqueapp_ ┆ false ┆ ristart_14 ┆ … ┆ false      ┆ false      ┆ false      ┆ train │
│ 329_reparat ┆ unique_623 ┆       ┆ 9329_repar ┆   ┆            ┆            ┆            ┆       │
│ ion         ┆ 8de54acc5d ┆       ┆ ation___un ┆   ┆            ┆            ┆            ┆       │
│             ┆ …          ┆       ┆ …          ┆   ┆            ┆            ┆            ┆       │
│ sarl_32_qua ┆ valdelia_1 ┆ false ┆ sarl_32_qu ┆ … ┆ false      ┆ true       ┆ false      ┆ train │
│ i_des_arts_ ┆ 85750      ┆       ┆ ai_des_art ┆   ┆            ┆            ┆            ┆       │
│ 198022_r…   ┆            ┆       ┆ s_198022_r ┆   ┆            ┆            ┆            ┆       │
│             ┆            ┆       ┆ …          ┆   ┆            ┆            ┆            ┆       │
│ tout_en_lib ┆ villedepar ┆ false ┆ tout_en_li ┆ … ┆ false      ┆ true       ┆ false      ┆ train │
│ ert_223131_ ┆ is_11      ┆       ┆ bert_22313 ┆   ┆            ┆            ┆            ┆       │
│ reparati…   ┆            ┆       ┆ 1_reparati ┆   ┆            ┆            ┆            ┆       │
│             ┆            ┆       ┆ …          ┆   ┆            ┆            ┆            ┆       │
│ uniqueapp_6 ┆ uniqueapp_ ┆ true  ┆ 1611794984 ┆ … ┆ false      ┆ false      ┆ false      ┆ train │
│ 2390b4bacc5 ┆ 623a1f3e52 ┆       ┆ 5187414423 ┆   ┆            ┆            ┆            ┆       │
│ d9001c0e…   ┆ 3f8a0019ee ┆       ┆            ┆   ┆            ┆            ┆            ┆       │
│             ┆ …          ┆       ┆            ┆   ┆            ┆            ┆            ┆       │
│ uniqueapp_u ┆ uniqueapp_ ┆ true  ┆ 1302091341 ┆ … ┆ false      ┆ false      ┆ false      ┆ train │
│ nique_62390 ┆ unique_623 ┆       ┆ 0658637646 ┆   ┆            ┆            ┆            ┆       │
│ 804d95b5…   ┆ a377d11d3b ┆       ┆            ┆   ┆            ┆            ┆            ┆       │
│             ┆ …          ┆       ┆            ┆   ┆            ┆            ┆            ┆       │
└─────────────┴────────────┴───────┴────────────┴───┴────────────┴────────────┴────────────┴───────┘

In [79]:
df_features_preprocessed_split.group_by("split").len()

shape: (2, 2)
┌───────┬──────┐
│ split ┆ len  │
│ ---   ┆ ---  │
│ str   ┆ u32  │
╞═══════╪══════╡
│ test  ┆ 399  │
│ train ┆ 1730 │
└───────┴──────┘

# Sauvegarde

In [80]:
df_features_preprocessed_split.write_parquet(
    DATASET_PATH.parent / f"features_{DATASET_PATH.stem}.parquet"
)